trigger:
- main
  
# pr:
#   branches:
#     include:
#       - dev

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'

- stage: test
  displayName: Test Python Code
  dependsOn:
  - build
  jobs:
  - job: test_python_solution
    displayName: test python solution
    steps:
    - task: UsePythonVersion@0
      inputs:
          versionSpec: '3.6'
    - script: python src/test_test1.py
